name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Run Linter
      - name: Run linter
        uses: hexlet/project-action@release
        run: make lint
